spring.application.name=nexus-backend

#spring.datasource.url=jdbc:postgresql://localhost:5432/nexus-ai
spring.datasource.url=postgresql://arijit:2PLwbEFi3K91zrE2O24vp8Jyh7AlbyA2@dpg-d870qvjbc2fs73cen5v0-a/nexus_g5ks

#spring.datasource.username=postgres
spring.datasource.username=arijit

#spring.datasource.password=Arijit2002@
spring.datasource.password=2PLwbEFi3K91zrE2O24vp8Jyh7AlbyA2

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#Authentication keys
jwt.secret=your_super_secret_key_which_should_be_very_long
jwt.expiration=86400000