package com.arijit.nexus_backend.ai.response.factory;

import com.arijit.nexus_backend.ai.response.dto.AIResponse;
import com.arijit.nexus_backend.ai.response.dto.ResponseSection;
import com.arijit.nexus_backend.ai.response.entity.SectionType;
import com.arijit.nexus_backend.ai.tool.entity.ToolCapability;
import com.arijit.nexus_backend.ai.tool.entity.ToolDomain;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@Component
public class LearningResponseFactory {

    public AIResponse buildLearningResponse(

            ToolCapability capability,

            String rawResponse

    ) {

        List<ResponseSection> sections =
                new ArrayList<>();

        String[] split =
                rawResponse.split("#");

        int order = 1;

        for (String part : split) {

            if (part.isBlank()) {
                continue;
            }

            sections.add(

                    ResponseSection.builder()

                            .sectionType(
                                    SectionType.ROADMAP
                            )

                            .title(
                                    "Learning Phase " + order
                            )

                            .content(
                                    part.trim()
                            )

                            .order(
                                    order
                            )

                            .importance(
                                    10 - order
                            )

                            .build()

            );

            order++;

        }

        return AIResponse.builder()

                .responseId(
                        UUID.randomUUID().toString()
                )

                .capability(
                        capability
                )

                .domain(
                        ToolDomain.LEARNING
                )

                .title(
                        "Learning Roadmap"
                )

                .summary(
                        "Structured learning response generated by Nexus AI"
                )

                .sections(
                        sections
                )

                .metadata(
                        Map.of(
                                "totalSections",
                                sections.size(),

                                "renderMode",
                                "ROADMAP"
                        )
                )

                .createdAt(
                        LocalDateTime.now()
                )

                .build();

    }

}