package com.arijit.nexus_backend.ai.tool.entity;

public enum ToolCapability {

    // GENERAL

    GENERAL_CHAT,
    KNOWLEDGE_EXPLANATION,
    QUESTION_ANSWERING,

    // CODE

    CODE_GENERATION,
    BUG_FIXING,
    CODE_REVIEW,
    CODE_EXPLANATION,
    API_GENERATION,
    DATABASE_DESIGN,
    SYSTEM_DESIGN,
    ARCHITECTURE_DESIGN,
    TEST_GENERATION,
    REFACTORING,

    // DOCUMENT

    RESUME_GENERATION,
    COVER_LETTER_GENERATION,
    DOCUMENT_SUMMARIZATION,

    // LEARNING

    ROADMAP_GENERATION,
    LEARNING_GUIDANCE,
    INTERVIEW_PREPARATION,

    // PRODUCTIVITY

    TASK_PLANNING,
    GOAL_BREAKDOWN,
    PROJECT_PLANNING,

    // MEMORY

    MEMORY_SEARCH,
    CONVERSATION_SUMMARY,

    // RESEARCH

    TECH_STACK_RECOMMENDATION,
    WEB_RESEARCH,
    COMPARISON_ANALYSIS,

    // AI

    PROMPT_ENGINEERING,
    AI_AGENT_DESIGN,
    RAG_ARCHITECTURE,

    // CREATIVE

    CONTENT_WRITING,
    BLOG_GENERATION,
    SOCIAL_MEDIA_CONTENT

}