package com.arijit.nexus_backend.ai.agent.architect.service;

import com.arijit.nexus_backend.ai.agent.architect.dto.ArchitecturePlan;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
@RequiredArgsConstructor
public class ArchitectAgentService {

    public ArchitecturePlan createPlan(
            String userRequest
    ) {

        String lower =
                userRequest.toLowerCase();

        List<String> technologies =
                detectTechnologies(lower);

        List<String> modules =
                detectModules(lower);

        List<String> files =
                determineFiles(modules);

        return ArchitecturePlan.builder()

                .projectType(
                        detectProjectType(lower)
                )

                .architectureStyle(
                        determineArchitecture(lower)
                )

                .technologies(
                        technologies
                )

                .modules(
                        modules
                )

                .files(
                        files
                )

                .reasoning(
                        "Generated by Architect Agent"
                )

                .build();

    }

    private String detectProjectType(
            String prompt
    ) {

        if (
                prompt.contains("spring boot")
        ) {

            return "SPRING_BOOT";

        }

        if (
                prompt.contains("react")
        ) {

            return "REACT";

        }

        return "GENERAL";

    }

    private String determineArchitecture(
            String prompt
    ) {

        if (
                prompt.contains("microservice")
        ) {

            return "MICROSERVICE";

        }

        return "LAYERED";

    }

    private List<String> detectTechnologies(
            String prompt
    ) {

        List<String> tech =
                new ArrayList<>();

        if (
                prompt.contains("spring boot")
        ) {

            tech.add("Spring Boot");

        }

        if (
                prompt.contains("postgresql")
        ) {

            tech.add("PostgreSQL");

        }

        if (
                prompt.contains("jwt")
        ) {

            tech.add("JWT");

        }

        return tech;

    }

    private List<String> detectModules(
            String prompt
    ) {

        List<String> modules =
                new ArrayList<>();

        if (
                prompt.contains("entity")
        ) {

            modules.add("Entity");

        }

        if (
                prompt.contains("repository")
        ) {

            modules.add("Repository");

        }

        if (
                prompt.contains("service")
        ) {

            modules.add("Service");

        }

        if (
                prompt.contains("controller")
        ) {

            modules.add("Controller");

        }

        if (
                prompt.contains("jwt")
        ) {

            modules.add("Security");

        }

        return modules;

    }

    private List<String> determineFiles(
            List<String> modules
    ) {

        List<String> files =
                new ArrayList<>();

        for (String module : modules) {

            switch (module) {

                case "Entity" ->
                        files.add(
                                "UserEntity.java"
                        );

                case "Repository" ->
                        files.add(
                                "UserRepository.java"
                        );

                case "Service" ->
                        files.add(
                                "UserService.java"
                        );

                case "Controller" ->
                        files.add(
                                "UserController.java"
                        );

                case "Security" -> {

                    files.add(
                            "SecurityConfig.java"
                    );

                    files.add(
                            "JwtService.java"
                    );

                }

            }

        }

        return files;

    }

}